export enum INDPRES {
	NOT_APPLYING = 0,
	FACE_TO_FACE_OPERATION = 1,
	NON_FACE_TO_FACE_OPERATION_INTERNET = 2,
	NON_FACE_TO_FACE_OPERATION_TELE = 3,
	NFCE_IN_OPERATION_HOME_DELIVERY = 4,
	FACE_TO_FACE_OPERATION_OFF_PREMISES = 5,
	NON_FACE_TO_FACE_OTHERS = 9
}

