export enum TPEMIS {
	NORMAL_ISSUER = 1,
	CONTINGENCY_FSIA = 2,
	CONTINGENCY_SCAN = 3,
	CONTINGENCY_DPEC = 4,
	CONTINGENCY_FSDA = 5,
	CONTINGENCY_SVCAN = 6,
	CONTINGENCY_SVCRS = 7,
	CONTINGENCY_OFFLINE_NFCE = 9
}
